<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampaignSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('campaign')->insert(['name' => 'The Duelist Kingdom', 'deck_name' => 'Monster Raider', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Heart of the Cards (Reverse)', 'deck_name' => 'Exodia Obliterate', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Heart of the Cards', 'deck_name' => 'Legendary Blue-Eyes', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Ultimate Great Moth (Reverse)', 'deck_name' => 'The Wasteland', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Ultimate Great Moth', 'deck_name' => 'Moth Evolution', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Harpie Lady (Reverse)', 'deck_name' => 'Thousand Years', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Harpie Lady', 'deck_name' => 'Harpie Lady', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Attack from the Deep (Reverse)', 'deck_name' => 'Attack the Moon', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Attack from the Deep', 'deck_name' => 'Legendary Ocean', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Dinosaur Duelist (Reverse)', 'deck_name' => 'Twin Battleguards', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Dinosaur Duelist', 'deck_name' => 'Red-Eyed Dinosaurs', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Evil Spirit of the Ring (Reverse)', 'deck_name' => 'Yugi\'s Friends', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Evil Spirit of the Ring', 'deck_name' => 'A Change of Heart', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'PaniK Attack (Reverse)', 'deck_name' => 'Fire the Catapult', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'PaniK Attack', 'deck_name' => 'The Dark Illusion', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Arena of Lost Souls (Reverse)', 'deck_name' => 'Shields and Swords', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Arena of Lost Souls', 'deck_name' => 'Rise of the Zombies', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Face Off (Reverse)', 'deck_name' => 'The Ultimate Dragon', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Face Off', 'deck_name' => 'Kuriboh Power', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A Duel of Tears (Reverse)', 'deck_name' => 'Little Fairies', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A Duel of Tears', 'deck_name' => 'Harpie Lady Sisters', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Champion vs. Creator (Reverse)', 'deck_name' => 'Car-tooned', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Champion vs. Creator', 'deck_name' => 'Crushing Victory', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Duel Identity (Reverse)', 'deck_name' => 'Black Luster Soldier', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Duel Identity', 'deck_name' => 'Harpie Lady 1', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Keith\'s Machinations (Reverse)', 'deck_name' => 'Armed Metal Dragon', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Keith\'s Machinations', 'deck_name' => 'Armed Metal Zoa', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Best Friends, Best Duelists (Reverse)', 'deck_name' => 'The Skull Dragon', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Best Friends, Best Duelists', 'deck_name' => 'Classic Fusion', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Match of the Millennium (Reverse)', 'deck_name' => 'Magician of Chaos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Match of the Millennium', 'deck_name' => 'Entering Toon World', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Mystery Duelist (Reverse)', 'deck_name' => 'Reflection Mirror', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Mystery Duelist', 'deck_name' => 'Zera to Infinity', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Battle City Begins (Reverse)', 'deck_name' => 'A Chain Destruction', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Battle City Begins', 'deck_name' => 'Cheating Exodia', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Master of Magicians (Reverse)', 'deck_name' => 'Dark Magician Girl', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Master of Magicians', 'deck_name' => 'Dark Magic', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Playing with a Parasite (Reverse)', 'deck_name' => 'Baby Dragon Fusion', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Playing with a Parasite', 'deck_name' => 'Insect Queen', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Mime Control (Reverse)', 'deck_name' => 'Deck Destruction', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Mime Control', 'deck_name' => 'Slime Revival', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Dark Spirit Revealed (Reverse)', 'deck_name' => 'Dark Magicians', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Dark Spirit Revealed', 'deck_name' => 'Final Destiny', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Awakening of Evil (Reverse)', 'deck_name' => 'Rocket Powered', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Awakening of Evil', 'deck_name' => 'Temple of the Kings', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A Duel With Destiny (Reverse)', 'deck_name' => 'Summoning Dragons', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A Duel With Destiny', 'deck_name' => 'Beyond the Grave', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Clash in the Colosseum (Reverse)', 'deck_name' => 'The Sky Dragon', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Clash in the Colosseum', 'deck_name' => 'The Tormentor', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Final Face Off (Reverse)', 'deck_name' => 'A Fiend\'s Sanctuary', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Final Face Off', 'deck_name' => 'Ra\'s Ascension', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A New Evil (Reverse)', 'deck_name' => 'The Legendary Hermos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A New Evil', 'deck_name' => 'Harpie of Orichalcos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Deja Duel (Reverse)', 'deck_name' => 'The Legendary Critias', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Deja Duel', 'deck_name' => 'Soldiers of Orichalcos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Fighting for a Friend (Reverse)', 'deck_name' => 'Lord with Red Eyes', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Fighting for a Friend', 'deck_name' => 'Machines of Orichalcos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Grappling with a Guardian (Reverse)', 'deck_name' => 'The Legendary Timaeus', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'Grappling with a Guardian', 'deck_name' => 'Guardians of Orichalcos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A Duel with Dartz! (Reverse)', 'deck_name' => 'Heart of the Dragons', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'A Duel with Dartz!', 'deck_name' => 'Power of Orichalcos', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Final Duel (Reverse)', 'deck_name' => 'The Final Duel', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Final Duel', 'deck_name' => 'The Ceremonial Duel', 'series_id' => 1]);
        DB::table('campaign')->insert(['name' => 'The Next King of Games', 'deck_name' => 'Ancient Golem', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Duel in Love (Reverse)', 'deck_name' => 'Flame Wing HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Duel in Love', 'deck_name' => 'Cyber Skater', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Shadow Duelist (Reverse)', 'deck_name' => 'Blade Edge HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Shadow Duelist', 'deck_name' => 'The Archfiend', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'For the Sake of Syrus (Reverse)', 'deck_name' => 'Cyber Dragons', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'For the Sake of Syrus', 'deck_name' => 'Transcendent Wings', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Formula for Success (Reverse)', 'deck_name' => 'Formula for Success', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Formula for Success', 'deck_name' => 'Chthonian Alliance', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Doomsday Duel (Reverse)', 'deck_name' => 'Wild Edge HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Doomsday Duel', 'deck_name' => 'Red-Eyes in Darkness', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Field of Screams (Reverse)', 'deck_name' => 'Shining Flare HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Field of Screams', 'deck_name' => 'Vampire Kingdom', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Duel Distrations (Reverse)', 'deck_name' => 'Clay Defender HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Duel Distrations', 'deck_name' => 'Amazoness Warrior', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Reason to Win (Reverse)', 'deck_name' => 'Cyber Blader', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Reason to Win', 'deck_name' => 'Skulls', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Amnaels Endgame (Reverse)', 'deck_name' => 'Electrum HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Amnaels Endgame', 'deck_name' => 'The Sun - Helios', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Rise of the Sacred Beasts (Reverse)', 'deck_name' => 'Philosopher\'s HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Rise of the Sacred Beasts', 'deck_name' => 'The Sacred Beasts', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Magna Chum Laude (Reverse)', 'deck_name' => 'An Ancient Gear', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Magna Chum Laude', 'deck_name' => 'Ayers Rock Sunrise', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Graduation Match (Reverse)', 'deck_name' => 'Future HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Graduation Match', 'deck_name' => 'Cyber Dragon Unite', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A New Breed of Hero (Reverse)', 'deck_name' => 'Dreadmaster Time', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A New Breed of Hero', 'deck_name' => 'Necro Heart HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Schooling the Master (Reverse)', 'deck_name' => 'Cyber Future', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Schooling the Master', 'deck_name' => 'The Cyber Ogres', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Blinded by the Light (Reverse)', 'deck_name' => 'Ojama HERO', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Blinded by the Light', 'deck_name' => 'The White Light', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Duel for Hire (Reverse)', 'deck_name' => 'Return to the Toon World', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Duel for Hire', 'deck_name' => 'Ancient Gears Explode', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Heart of Ice (Reverse)', 'deck_name' => 'HERO Neos Arrives', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Heart of Ice', 'deck_name' => 'White Destruction', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Tough Love (Reverse)', 'deck_name' => 'Cyberdark Impact', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Tough Love', 'deck_name' => 'Vehicle-roid Bond', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Hand of Justice (Reverse)', 'deck_name' => 'HERO Grand Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Hand of Justice', 'deck_name' => 'Arcana Force', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Future Changes (Reverse)', 'deck_name' => 'The Ojama Magic', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Future Changes', 'deck_name' => 'Pixie Power', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Jewel of a Duel (Reverse)', 'deck_name' => 'HERO Air Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Jewel of a Duel', 'deck_name' => 'Crystal Beast', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Hanging with Axel (Reverse)', 'deck_name' => 'HERO Flare Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Hanging with Axel', 'deck_name' => 'Volcanic Accelerator', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Primal Instinct (Reverse)', 'deck_name' => 'Hard as a Rock', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Primal Instinct', 'deck_name' => 'Dino Tyranno', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Head in the Clouds (Reverse)', 'deck_name' => 'In the Cloudian', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Head in the Clouds', 'deck_name' => 'XYZ Ojama', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Snake in the Grass (Reverse)', 'deck_name' => 'HERO Magma Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Snake in the Grass', 'deck_name' => 'Venomous Reptiles', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Dimensional Duel (Reverse)', 'deck_name' => 'Rainbow Crystals', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'A Dimensional Duel', 'deck_name' => 'Cyberdark Overload', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Unleashing the Dragon (Reverse)', 'deck_name' => 'HERO Chaos Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Unleashing the Dragon', 'deck_name' => 'Phantasm Armityle', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Power Within (Reverse)', 'deck_name' => 'Rainbow Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Power Within', 'deck_name' => 'Dark Rainbow', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Return of the Supreme King (Reverse)', 'deck_name' => 'Super Polymerization', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Return of the Supreme King', 'deck_name' => 'Ultimate Nightmare', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Darkness Returns (Reverse)', 'deck_name' => 'HERO Divine Neos', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Darkness Returns', 'deck_name' => 'Overwhelming Darkness', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Legendary Duelist (Reverse)', 'deck_name' => 'Hero Behind the Mask', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'The Legendary Duelist', 'deck_name' => 'The Legendary Duelist', 'series_id' => 2]);
        DB::table('campaign')->insert(['name' => 'Ready, Set, Duel', 'deck_name' => 'Security Dogs', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'A Blast from the Past (Reverse)', 'deck_name' => 'Junk Warrior', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'A Blast from the Past', 'deck_name' => 'Red Dragon Resonator', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Facility (Reverse)', 'deck_name' => 'Treasure Deck', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Facility', 'deck_name' => 'Raging Battle Ox', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Lockdown Duel (Reverse)', 'deck_name' => 'Gift from the Inmates', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Lockdown Duel', 'deck_name' => 'Iron Chain Laws', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Take Back (Reverse)', 'deck_name' => 'Turbo Warrior', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Take Back', 'deck_name' => 'The Law Enforcers', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Welcome to the Fortune Cup (Reverse)', 'deck_name' => 'Stop Reactor', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Welcome to the Fortune Cup', 'deck_name' => 'Mighty Morphtronic', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Surprise Surprise (Reverse)', 'deck_name' => 'Nitro Warrior', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Surprise Surprise', 'deck_name' => 'Supersonic Skulls', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Second Round Showdown (Reverse)', 'deck_name' => 'Armory Warrior', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Second Round Showdown', 'deck_name' => 'Dark Strike Reactor', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Duel of Dragons (Reverse)', 'deck_name' => 'Stardust Prevention', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Duel of Dragons', 'deck_name' => 'Phoenixian Black Rose', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Fortune Cup Finale (Reverse)', 'deck_name' => 'Stardust Junk', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Fortune Cup Finale', 'deck_name' => 'Red Dragon Marauder', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Supersensory Shakedown (Reverse)', 'deck_name' => 'Psychic Ruler', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Supersensory Shakedown', 'deck_name' => 'Morphtronic Power Tool', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Digging Deeper (Reverse)', 'deck_name' => 'Psychic Nightmare', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Digging Deeper', 'deck_name' => 'Lost Fortune', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Mark of the Monkey (Reverse)', 'deck_name' => 'Mega Morphtronic', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Mark of the Monkey', 'deck_name' => 'Immortal Cusillu', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'A Whale of a Ride (Reverse)', 'deck_name' => 'Blackwing Master', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'A Whale of a Ride', 'deck_name' => 'Immortal Chace Chalhua', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'A Score to Settle (Reverse)', 'deck_name' => 'Stardust Majestic', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'A Score to Settle', 'deck_name' => 'Immortal Ccapac Apu', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Destiny\'s Will (Reverse)', 'deck_name' => 'Stardust Road', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Destiny\'s Will', 'deck_name' => 'Immortal Uru', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Shadows of Doubt (Reverse)', 'deck_name' => 'Red Dragon Majesty', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Shadows of Doubt', 'deck_name' => 'Immortal Aslla Piscu', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Truth and Consequences (Reverse)', 'deck_name' => 'Dark Black Rose', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Truth and Consequences', 'deck_name' => 'Immortal Ccarayhua', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Signs of Doom (Reverse)', 'deck_name' => 'Archer Stardust', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Signs of Doom', 'deck_name' => 'Immortal Goodwin', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'French Twist (Reverse)', 'deck_name' => 'Stardust Starlight', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'French Twist', 'deck_name' => 'Joan de Fleus', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Edge of Elimination Part 1 (Reverse)', 'deck_name' => 'Stardust Breaker', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Edge of Elimination Part 1', 'deck_name' => 'One Horn Thunder', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Edge of Elimination Part 2 (Reverse)', 'deck_name' => 'Stardust Destroyer', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Edge of Elimination Part 2', 'deck_name' => 'Two Horn Voltic', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Edge of Elimination Part 3 (Reverse)', 'deck_name' => 'Stardust Dragon Knight', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Edge of Elimination Part 3', 'deck_name' => 'Three Horn Lighting', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Duel for Redemption (Reverse)', 'deck_name' => 'Red Dragon Nova', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Duel for Redemption', 'deck_name' => 'Thor the Lord', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Tricking the Trickster (Reverse)', 'deck_name' => 'Blackwing Dragon', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Tricking the Trickster', 'deck_name' => 'Loki the Lord', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Tricking the Trickster 2 (Reverse)', 'deck_name' => 'Stardust Shooting Star', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Tricking the Trickster 2', 'deck_name' => 'Odin the Father', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Beginning of the End (Reverse)', 'deck_name' => 'Red Dragon Guardian', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'The Beginning of the End', 'deck_name' => 'Meklord Infitiny', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Dawn of the Machines (Reverse)', 'deck_name' => 'Red Dragon Pride', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Dawn of the Machines', 'deck_name' => 'Meklord Emperor', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Victory of Doom (Reverse)', 'deck_name' => 'Stardust Dragons', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Victory of Doom', 'deck_name' => 'Meklord Mekanikle', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Fight for the Future (Reverse)', 'deck_name' => 'Stardust Formula', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Fight for the Future', 'deck_name' => 'TG-1DER', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Hope (Reverse)', 'deck_name' => 'Quasar Dragon', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Hope', 'deck_name' => 'The End of Time', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Future Path (Reverse)', 'deck_name' => 'Junk Power', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Future Path', 'deck_name' => 'Red Dragon Blader', 'series_id' => 3]);
        DB::table('campaign')->insert(['name' => 'Go with the Flow', 'deck_name' => 'Leviathan Shark', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Flipping Out (Reverse)', 'deck_name' => 'A Baby Tiragon', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Flipping Out', 'deck_name' => 'Flipping Pain', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The Sparrow (Reverse)', 'deck_name' => 'Utopian Paradise', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The Sparrow', 'deck_name' => 'Esper Star Sparrow', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Feline Frenzy (Reverse)', 'deck_name' => 'Sting of the Swordsman', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Feline Frenzy', 'deck_name' => 'Cat-tastrophe', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Roots of the Problem (Reverse)', 'deck_name' => 'The Iron Will', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Roots of the Problem', 'deck_name' => 'Shrouding Dark Mist', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Love Hurts (Reverse)', 'deck_name' => 'Feel the Temtempo', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Love Hurts', 'deck_name' => 'Rail Kaboom', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Double Jeopardy (Reverse)', 'deck_name' => 'Utopian Chaos', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Double Jeopardy', 'deck_name' => 'Butterflight', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The Dragon Awakens (Reverse)', 'deck_name' => 'Photon Galaxies', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The Dragon Awakens', 'deck_name' => 'Chronomaly Relics', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Cosmic Chaos (Reverse)', 'deck_name' => 'Photon Galaxy Zero', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Cosmic Chaos', 'deck_name' => 'The Tannhauser Gate', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Swimming with Sharks (Reverse)', 'deck_name' => 'Shark Attack', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Swimming with Sharks', 'deck_name' => 'Gimmick Puppetry', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Rockin\' and Rollin\' (Reverse)', 'deck_name' => 'Utopian Cowboy', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Rockin\' and Rollin\'', 'deck_name' => 'Heroic', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Duel of Destiny (Reverse)', 'deck_name' => 'Go Go Go!', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Duel of Destiny', 'deck_name' => 'Shark Chaos', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Sphere of Fear (Reverse)', 'deck_name' => 'Utopian Weapons', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Sphere of Fear', 'deck_name' => 'A Heraldry Art', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'A Trio\'s Challenge (Reverse)', 'deck_name' => 'Utopian Shield', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'A Trio\'s Challenge', 'deck_name' => 'Heart Earth', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Counter Offensive (Reverse)', 'deck_name' => 'Utopian Claw', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Counter Offensive', 'deck_name' => 'Cross Counter', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Dual Duel (Reverse)', 'deck_name' => 'Utopian V', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Dual Duel', 'deck_name' => 'Strong Hands', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Search for Shadows, Pt. 1 (Reverse)', 'deck_name' => 'Shark Capture', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Search for Shadows, Pt. 1', 'deck_name' => 'Thunder Star Seraph', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Search for Shadows, Pt. 2 (Reverse)', 'deck_name' => 'Neo Galaxy Photon', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Search for Shadows, Pt. 2', 'deck_name' => 'Neo Galaxy Tachyon', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Search for Shadows, Pt. 3 (Reverse)', 'deck_name' => 'Utopian Victory', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Search for Shadows, Pt. 3', 'deck_name' => 'Dark Umbral Horror', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Barian Vengeance (Reverse)', 'deck_name' => 'Utopian Champion', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Barian Vengeance', 'deck_name' => 'Heart of a Lion', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'A Sea of Troubles (Reverse)', 'deck_name' => 'Black Ray Lancer', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'A Sea of Troubles', 'deck_name' => 'Gorgonic Mermail', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'A World of Chaos (Reverse)', 'deck_name' => 'Utopian Armor', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'A World of Chaos', 'deck_name' => 'Thunderous Dark Storm', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Clash of the Emperors (Reverse)', 'deck_name' => 'The Seventh One', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Clash of the Emperors', 'deck_name' => 'Admiration of 1000', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The New World (Reverse)', 'deck_name' => 'Utopian Force', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The New World', 'deck_name' => 'The Chaos Throne', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The Battle of Three Worlds (Reverse)', 'deck_name' => 'Utopian Beyond', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'The Battle of Three Worlds', 'deck_name' => 'Last Barian Hope', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Forever ZEXAL (Reverse)', 'deck_name' => 'Go Go Go! Gagaga!', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Forever ZEXAL', 'deck_name' => 'Astral Force', 'series_id' => 4]);
        DB::table('campaign')->insert(['name' => 'Swing Into Action', 'deck_name' => 'The Wild Battleguards', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Trade Bait (Reverse)', 'deck_name' => 'Pendulum Block', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Trade Bait', 'deck_name' => 'Blazing Darts', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Dueling with the Stars (Reverse)', 'deck_name' => 'Star and Timegazer', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Dueling with the Stars', 'deck_name' => 'Star of the Constellar', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'You Show \'Em! (Reverse)', 'deck_name' => 'Gem-Knight Pressure', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'You Show \'Em!', 'deck_name' => 'Melodious Diva\'s Ballad', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Going, Going, Going (Reverse)', 'deck_name' => 'Path of the Samurai', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Going, Going, Going', 'deck_name' => 'X-Saber Striker', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Date With Fate (Reverse)', 'deck_name' => 'View of Rune-Eyes', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Date With Fate', 'deck_name' => 'Princess\' Prediction', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Fusion Foes (Reverse)', 'deck_name' => 'Melodious Choir\'s Song', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Fusion Foes', 'deck_name' => 'Gem-Knight Brilliance', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'The Pendulum Swings Both Ways (Reverse)', 'deck_name' => 'Wrath of Beast-Eyes', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'The Pendulum Swings Both Ways', 'deck_name' => 'Winds of Yosenju', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Making the Cut (Reverse)', 'deck_name' => 'Raidraptor Revolution', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Making the Cut', 'deck_name' => 'Frightfur Fusion Factory', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Dark Reflection (Reverse)', 'deck_name' => 'Hi-Speed Clear Wing', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Dark Reflection', 'deck_name' => 'The Dark Rebellion', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Obelisk Assault (Reverse)', 'deck_name' => 'Lunalight Fight', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Obelisk Assault', 'deck_name' => 'Peformage Magicians', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Battlefronts (Reverse)', 'deck_name' => 'The Shogun Ninja', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Battlefronts', 'deck_name' => 'Hunt of the Ancient Gear', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Fighting for Fun (Reverse)', 'deck_name' => 'Odd-Eyes Rebellion', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Fighting for Fun', 'deck_name' => 'Frightfur Fury', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'City \'Scape (Reverse)', 'deck_name' => 'Hi-Speed Dice battle', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'City \'Scape', 'deck_name' => 'Goyo Chase', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Crow\'s Crew (Reverse)', 'deck_name' => 'Blackwing Typhoon', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Crow\'s Crew', 'deck_name' => 'Superheavy Pendulum', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Concerted Effort (Reverse)', 'deck_name' => 'Melodious Maestra\'s Fortissimo', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Concerted Effort', 'deck_name' => 'Flower Cardian Koi Koi', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Turbotainers (Reverse)', 'deck_name' => 'Raidraptor Doom', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Turbotainers', 'deck_name' => 'Ancient Performage', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Battle Birds (Reverse)', 'deck_name' => 'Blackwing Bombardment', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Battle Birds', 'deck_name' => 'Ultimate Raidraptor', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'The Many Dimensions of Yuya (Reverse)', 'deck_name' => 'Odd-Eyes Xyz', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'The Many Dimensions of Yuya', 'deck_name' => 'Blackwing Assault', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Chain Game (Reverse)', 'deck_name' => 'Hi-Speed Recovery', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Chain Game', 'deck_name' => 'Starving Venim Predaplant', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Friendship Finale (Reverse)', 'deck_name' => 'Performapal Synchro Paladin', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Friendship Finale', 'deck_name' => 'Scarlet Red', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Vicious Cycle (Reverse)', 'deck_name' => 'D/D/D King', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Vicious Cycle', 'deck_name' => 'Ancient Gear Assault', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Rush to Revenge (Reverse)', 'deck_name' => 'Odd-Eyes Dragoncaller', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Rush to Revenge', 'deck_name' => 'Cipher Galaxy', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Rise of the Resistance (Reverse)', 'deck_name' => 'Cyber Machine Angel', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Rise of the Resistance', 'deck_name' => 'Strike of the Metalfoes', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Last Laugh (Reverse)', 'deck_name' => 'Smiling Peformance', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Last Laugh', 'deck_name' => 'Dystopian Destiny', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'All Duel Hands on Desk (Reverse)', 'deck_name' => 'Neo Cipher Galaxy', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'All Duel Hands on Desk', 'deck_name' => 'Perfomage Gear', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Grip of the Parasite (Reverse)', 'deck_name' => 'Ring of the Windwitch', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Grip of the Parasite', 'deck_name' => 'Hi-Speed Crystal Wing', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Family Face Off (Reverse)', 'deck_name' => 'Rise of the Raidraptor', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Family Face Off', 'deck_name' => 'Wings of Lyrilusc', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Duel Interrupted (Reverse)', 'deck_name' => 'Greedy Venom Predaplant', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Duel Interrupted', 'deck_name' => 'Hi-Speed Shock', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Time to Reunite (Reverse)', 'deck_name' => 'Odd-Eyes Break Away', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'Time to Reunite', 'deck_name' => 'Starving Wing', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Ray of Hope (Reverse)', 'deck_name' => 'D/D/D High King', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'A Ray of Hope', 'deck_name' => 'Supreme King', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'One Last Duel (Reverse)', 'deck_name' => 'Odd-Eyes Dragons', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'One Last Duel', 'deck_name' => 'D/D/D Super Doom King', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'That\'s a Wrap! (Reverse)', 'deck_name' => 'Odd-Eyes Pendulum Dragons', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'That\'s a Wrap!', 'deck_name' => 'Magician\'s Hand', 'series_id' => 5]);
        DB::table('campaign')->insert(['name' => 'My Name Is Playmaker', 'deck_name' => 'Hacking Storm', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'The Three Count Rings (Reverse)', 'deck_name' => 'Link the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'The Three Count Rings', 'deck_name' => 'Gouki Match', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Hanoi\'s Angel (Reverse)', 'deck_name' => 'Encode the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Hanoi\'s Angel', 'deck_name' => 'Trickstar Stage', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A Storm is Coming (Reverse)', 'deck_name' => 'Firewall in Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A Storm is Coming', 'deck_name' => 'Rokket Fire', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Ghost Gal\'s Invitation (Reverse)', 'deck_name' => 'Excode the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Ghost Gal\'s Invitation', 'deck_name' => 'Altergeist Protocol', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Dueling for Answers (Reverse)', 'deck_name' => 'Gauge the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Dueling for Answers', 'deck_name' => 'Acute Tindangle', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Under VRAINS (Reverse)', 'deck_name' => 'Bomber Rokket', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Under VRAINS', 'deck_name' => 'Altergeist Manifestation', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Once Upon a Time (Reverse)', 'deck_name' => 'Angelic Aroma', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Once Upon a Time', 'deck_name' => 'Trickstar Theater', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A Bridge Too Far (Reverse)', 'deck_name' => 'Powercode the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A Bridge Too Far', 'deck_name' => 'World Aroma', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Gore at War (Reverse)', 'deck_name' => 'Rokket Sword', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Gore at War', 'deck_name' => 'Gouki Fight', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Link to the Future (Reverse)', 'deck_name' => 'Transcode the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Link to the Future', 'deck_name' => 'Borrel Rokket', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'The Bounty Hunter (Reverse)', 'deck_name' => 'Clock the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'The Bounty Hunter', 'deck_name' => 'Mecha Phantom Flier', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Blue Gal\'s Here! (Reverse)', 'deck_name' => 'Salamangreat Heat', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Blue Gal\'s Here!', 'deck_name' => 'Trickstar Concert', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Tuning Rokkets (Reverse)', 'deck_name' => 'Savage Rokket', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Tuning Rokkets', 'deck_name' => 'Dragunity Romulus', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Battle of the Siblings (Reverse)', 'deck_name' => 'Mecha Phantom Fighter', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Battle of the Siblings', 'deck_name' => 'Altergeiste Tuning', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Friend or Foe (Reverse)', 'deck_name' => 'Gumblar Rokket', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Friend or Foe', 'deck_name' => 'Mecha Phantom Raptor', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Specter\'s Plan (Reverse)', 'deck_name' => 'Noble King', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Specter\'s Plan', 'deck_name' => 'Blossoming Aroma', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Windy\'s Revenge (Reverse)', 'deck_name' => 'Salamangreat Burner', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Windy\'s Revenge', 'deck_name' => 'Dragunity Divine', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A New World Coming (Reverse)', 'deck_name' => 'Attributes Invoked', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A New World Coming', 'deck_name' => 'Marincess Ocean', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Burning Soul (Reverse)', 'deck_name' => 'Attributes Shadowed', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Burning Soul', 'deck_name' => 'Salamangreat Inferno', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Anything to Win (Reverse)', 'deck_name' => 'Encharge Rokket', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Anything to Win', 'deck_name' => 'Noble High Ruler', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A Wish Entrusted (Reverse)', 'deck_name' => 'Darkfluid in Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'A Wish Entrusted', 'deck_name' => 'Attributes Altered', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Go Go Roboppi! (Reverse)', 'deck_name' => 'Morphtronic Appliances', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Go Go Roboppi!', 'deck_name' => 'Phantomgeist', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Unbreakable Spirit (Reverse)', 'deck_name' => 'AI Need It', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Unbreakable Spirit', 'deck_name' => 'Gouki Bout', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Ai\'s Conundrum (Reverse)', 'deck_name' => 'AI Adore It', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Ai\'s Conundrum', 'deck_name' => 'Marincess Tindangle', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Roboppi\'s Dream (Reverse)', 'deck_name' => 'Salamangreat Blaze', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Roboppi\'s Dream', 'deck_name' => 'Morphtronic Devices', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Back to the Beginning (Reverse)', 'deck_name' => 'Salamangreat Fire', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Back to the Beginning', 'deck_name' => 'Topologic Rokket', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Separate Ways (Reverse)', 'deck_name' => 'Into the Cyberse', 'series_id' => 6]);
        DB::table('campaign')->insert(['name' => 'Separate Ways', 'deck_name' => 'AI Love It', 'series_id' => 6]);
    }
}
