<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChallengeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('challenge')->insert(['deck_name' => 'Dragon Buster', 'duelist_id' => 1, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Dark Magician Attack', 'duelist_id' => 2, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Pendulum Scraps', 'duelist_id' => 3, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Armageddon', 'duelist_id' => 4, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Serene Aroma', 'duelist_id' => 5, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Spellbook Prophecy', 'duelist_id' => 6, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Restraint of Jinzo', 'duelist_id' => 7, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Sign of the Harpie', 'duelist_id' => 8, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Ritual of the Gishki', 'duelist_id' => 9, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Sweets from Madolche', 'duelist_id' => 10, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Gravekeepers', 'duelist_id' => 11, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Tricks of Pumprincess', 'duelist_id' => 12, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Super Soldier', 'duelist_id' => 13, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Rise of the Evolsaur', 'duelist_id' => 14, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Coming of Exodia', 'duelist_id' => 15, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Wrath of the Dragon', 'duelist_id' => 16, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Trail of Slime', 'duelist_id' => 17, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Master Herald', 'duelist_id' => 18, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'PSY-Frame Assembly', 'duelist_id' => 19, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Inzektor Swarm', 'duelist_id' => 20, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'FINAL', 'duelist_id' => 21, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Legend of the Fiend', 'duelist_id' => 22, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'The Spellcasters\' Stone', 'duelist_id' => 23, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Rise of Skull Servants', 'duelist_id' => 24, 'series_id' => 1]);
        DB::table('challenge')->insert(['deck_name' => 'Eye of the Cloudian', 'duelist_id' => 25, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Ice Barrier', 'duelist_id' => 26, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Obey the Alien', 'duelist_id' => 27, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'A Hero\'s Destiny', 'duelist_id' => 28, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Tri-Blaze Volcanic', 'duelist_id' => 29, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Carbon Formula', 'duelist_id' => 30, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Bad Reactions', 'duelist_id' => 31, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Shadow of the Vampire', 'duelist_id' => 32, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Gray Kaiju', 'duelist_id' => 33, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Last Level of the Dragon', 'duelist_id' => 34, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Sunrise over Oz', 'duelist_id' => 35, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Ancient Gear Rebuilt', 'duelist_id' => 36, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Courage of the Hero', 'duelist_id' => 37, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Artifact Vault', 'duelist_id' => 38, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Rock Bombardment', 'duelist_id' => 39, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Strike of the Ninja', 'duelist_id' => 40, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Advent of Exodia', 'duelist_id' => 41, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Unskilled Beast', 'duelist_id' => 42, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Dark Underworld', 'duelist_id' => 43, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Invasion of the Worms', 'duelist_id' => 44, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Swing of the Pendulum', 'duelist_id' => 45, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Geargia Karakuri', 'duelist_id' => 46, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Brave Amazoness', 'duelist_id' => 47, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'The Ghostrick Surprise', 'duelist_id' => 48, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Heart of the Jurrac', 'duelist_id' => 49, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Lightsworn Judgement', 'duelist_id' => 50, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Cyber Dragon Impact', 'duelist_id' => 51, 'series_id' => 2]);
        DB::table('challenge')->insert(['deck_name' => 'Black Rose Garden', 'duelist_id' => 52, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Phoenix Rises', 'duelist_id' => 53, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Tech Genus', 'duelist_id' => 54, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Crash of the Qliphort', 'duelist_id' => 55, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Fabled Awakening', 'duelist_id' => 56, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Spiritual Beast', 'duelist_id' => 57, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Electrifying Watt', 'duelist_id' => 58, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Fortune Lady\'s Luck', 'duelist_id' => 59, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Flight of the Blackwing', 'duelist_id' => 60, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Moja King', 'duelist_id' => 61, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Nordic Beast of Aesir', 'duelist_id' => 62, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Ultimate Athletes', 'duelist_id' => 63, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Tribes of the Gusto', 'duelist_id' => 64, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Fire King Onslaught', 'duelist_id' => 65, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Fires of the Flamvell', 'duelist_id' => 66, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Gladiator Beasts', 'duelist_id' => 67, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'For All Infernity', 'duelist_id' => 68, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Enhance the Genex Ally', 'duelist_id' => 69, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'In Dark World', 'duelist_id' => 70, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Paralyzing Reptilliane', 'duelist_id' => 71, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Power the Batteryman', 'duelist_id' => 72, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Malefic Truth', 'duelist_id' => 73, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Yang Zing Radiance', 'duelist_id' => 74, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Traptrix Ambush', 'duelist_id' => 75, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Mind of the Psychic', 'duelist_id' => 76, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'The Noble Knights', 'duelist_id' => 77, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Legendary Six Samurai', 'duelist_id' => 78, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Stardust Dragon Assault', 'duelist_id' => 79, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Ascension of the Vylon', 'duelist_id' => 80, 'series_id' => 3]);
        DB::table('challenge')->insert(['deck_name' => 'Spirit fo the Boxer', 'duelist_id' => 81, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Mecha Phantom Beasts', 'duelist_id' => 82, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Utopia Force', 'duelist_id' => 83, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Tin Archduke\'s Order', 'duelist_id' => 84, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Wind-Up the Zenmai', 'duelist_id' => 85, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'The Sylvan Blessings', 'duelist_id' => 86, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Void of the Infernoid', 'duelist_id' => 87, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Hazy Flame Rebirth', 'duelist_id' => 88, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Rising Star Seraph', 'duelist_id' => 89, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Bite of the Chewbone', 'duelist_id' => 90, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'The Ronin Raccoon', 'duelist_id' => 91, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Hieratic Sun Dragon', 'duelist_id' => 92, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Dragunity Knights', 'duelist_id' => 93, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Atlantean Marksman', 'duelist_id' => 94, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Wind from Mist Valley', 'duelist_id' => 95, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Fire Fist Brotherhood', 'duelist_id' => 96, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Evilswarm Annihilation', 'duelist_id' => 97, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Shadow Shaddoll', 'duelist_id' => 98, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Dyson Sphere Blast', 'duelist_id' => 99, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Serenity of the Naturia', 'duelist_id' => 100, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Mermail or the Abyss', 'duelist_id' => 101, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Frog Metamorphosis', 'duelist_id' => 102, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Karakuri', 'duelist_id' => 103, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Inzektors of Orichalcos', 'duelist_id' => 104, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Power of the Nekroz', 'duelist_id' => 105, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Rise of Dark Simorgh', 'duelist_id' => 106, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'The Xyz Warrior', 'duelist_id' => 107, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Bujin Reincarnation', 'duelist_id' => 108, 'series_id' => 4]);
        DB::table('challenge')->insert(['deck_name' => 'Spirit of the Shinobird', 'duelist_id' => 26, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Caves of the Subterror', 'duelist_id' => 28, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Shadow Prediction', 'duelist_id' => 109, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Draco-Amorphage', 'duelist_id' => 110, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Rise of the Shiranui', 'duelist_id' => 111, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Forming the Crystron', 'duelist_id' => 60, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Zefra Divine Strike', 'duelist_id' => 112, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Rank-Up Clowns', 'duelist_id' => 113, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Beyond the Constellar', 'duelist_id' => 114, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Superheavy Defender', 'duelist_id' => 115, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'The True Draco', 'duelist_id' => 66, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Age of the Paleozoic', 'duelist_id' => 116, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Gem-Knight Resistance', 'duelist_id' => 117, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'XX-Saber Slash', 'duelist_id' => 118, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'The Burning Abyss', 'duelist_id' => 92, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Monsters Fur Hire', 'duelist_id' => 119, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Ninja Transformation', 'duelist_id' => 120, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Magnet Warriot Force', 'duelist_id' => 121, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Goyo Confiscation', 'duelist_id' => 122, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Beasts of the Zoodiac', 'duelist_id' => 123, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Black Raid', 'duelist_id' => 124, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'The Frightful Fluffal', 'duelist_id' => 125, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Mega Monarch', 'duelist_id' => 126, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Triamid Techonology', 'duelist_id' => 127, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Clear Wing', 'duelist_id' => 128, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Meltdown Invoked', 'duelist_id' => 129, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'The Spellcasters\' Stone', 'duelist_id' => 130, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Stellarknight Nova Blast', 'duelist_id' => 131, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'The Pendulum Magicians', 'duelist_id' => 132, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Charge of the Dinomist', 'duelist_id' => 133, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Melodious Diva\'s Solo', 'duelist_id' => 134, 'series_id' => 5]);
        DB::table('challenge')->insert(['deck_name' => 'Creeping Vendread', 'duelist_id' => 135, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Creepy Krawler', 'duelist_id' => 136, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Trickstar Grand Arena', 'duelist_id' => 137, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Metaphysical', 'duelist_id' => 138, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Legendary Fisherman', 'duelist_id' => 139, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Elemental Lord', 'duelist_id' => 140, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Secret Six', 'duelist_id' => 141, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'The Silent Warrior', 'duelist_id' => 142, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Hunder and Light', 'duelist_id' => 143, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Link Light', 'duelist_id' => 144, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Formula Athlete', 'duelist_id' => 145, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Rekindled Laval', 'duelist_id' => 146, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Light and Darkness', 'duelist_id' => 147, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Chemicritter Reaction', 'duelist_id' => 148, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Golden Castle', 'duelist_id' => 148, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'International SPYRAL', 'duelist_id' => 149, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Burning Mirrors', 'duelist_id' => 150, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Avenging Fairies', 'duelist_id' => 150, 'series_id' => 6]);
        DB::table('challenge')->insert(['deck_name' => 'Sky Strikerss', 'duelist_id' => 151, 'series_id' => 6]);

    }
}
