<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DuelistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('duelist')->insert(['name' => 'Alister']);
        DB::table('duelist')->insert(['name' => 'Arkana']);
        DB::table('duelist')->insert(['name' => 'Bandit Keith']);
        DB::table('duelist')->insert(['name' => 'Bonz']);
        DB::table('duelist')->insert(['name' => 'Dartz']);
        DB::table('duelist')->insert(['name' => 'Ishizu Ishtar']);
        DB::table('duelist')->insert(['name' => 'Joey Wheeler']);
        DB::table('duelist')->insert(['name' => 'Mai Valentine']);
        DB::table('duelist')->insert(['name' => 'Mako Tsunami']);
        DB::table('duelist')->insert(['name' => 'Maximillion Pegasus']);
        DB::table('duelist')->insert(['name' => 'Odion']);
        DB::table('duelist')->insert(['name' => 'PaniK']);
        DB::table('duelist')->insert(['name' => 'Rafael']);
        DB::table('duelist')->insert(['name' => 'Rex Raptor']);
        DB::table('duelist')->insert(['name' => 'Seeker']);
        DB::table('duelist')->insert(['name' => 'Seto Kaiba']);
        DB::table('duelist')->insert(['name' => 'Strings']);
        DB::table('duelist')->insert(['name' => 'Téa Gardner']);
        DB::table('duelist')->insert(['name' => 'Valon']);
        DB::table('duelist')->insert(['name' => 'Weevil Underwood']);
        DB::table('duelist')->insert(['name' => 'Yami Bakura']);
        DB::table('duelist')->insert(['name' => 'Yami Marik']);
        DB::table('duelist')->insert(['name' => 'Yami Yugi']);
        DB::table('duelist')->insert(['name' => 'Yugi Muto']);
        DB::table('duelist')->insert(['name' => 'Adrian Gecko']);
        DB::table('duelist')->insert(['name' => 'Alexis Rhodes']);
        DB::table('duelist')->insert(['name' => 'Amnael']);
        DB::table('duelist')->insert(['name' => 'Aster Phoenix']);
        DB::table('duelist')->insert(['name' => 'Axel Brodie']);
        DB::table('duelist')->insert(['name' => 'Bastion Misawa']);
        DB::table('duelist')->insert(['name' => 'Blair Flannigan']);
        DB::table('duelist')->insert(['name' => 'Camula']);
        DB::table('duelist')->insert(['name' => 'Chancellor Sheppard']);
        DB::table('duelist')->insert(['name' => 'Chazz Princeton']);
        DB::table('duelist')->insert(['name' => 'Chumley Huffington']);
        DB::table('duelist')->insert(['name' => 'Dr. Vellian Crowler']);
        DB::table('duelist')->insert(['name' => 'Jaden Yuki']);
        DB::table('duelist')->insert(['name' => 'Jesse Anderson']);
        DB::table('duelist')->insert(['name' => 'Jim Crocodile Cook']);
        DB::table('duelist')->insert(['name' => 'Kagemaru']);
        DB::table('duelist')->insert(['name' => 'Marcel Bonaparte']);
        DB::table('duelist')->insert(['name' => 'Masked Atticus']);
        DB::table('duelist')->insert(['name' => 'Nightshroud']);
        DB::table('duelist')->insert(['name' => 'Prof. Thelonious Viper']);
        DB::table('duelist')->insert(['name' => 'Sartorius Kumar']);
        DB::table('duelist')->insert(['name' => 'Syrus Truesdale']);
        DB::table('duelist')->insert(['name' => 'Tania']);
        DB::table('duelist')->insert(['name' => 'Titan']);
        DB::table('duelist')->insert(['name' => 'Tyranno Hassleberry']);
        DB::table('duelist')->insert(['name' => 'Yubel']);
        DB::table('duelist')->insert(['name' => 'Zane Truesdale']);
        DB::table('duelist')->insert(['name' => 'Akiza Izinski']);
        DB::table('duelist')->insert(['name' => 'Andre']);
        DB::table('duelist')->insert(['name' => 'Antinomy']);
        DB::table('duelist')->insert(['name' => 'Aporia']);
        DB::table('duelist')->insert(['name' => 'Bolt Tanner']);
        DB::table('duelist')->insert(['name' => 'Breo']);
        DB::table('duelist')->insert(['name' => 'Broder']);
        DB::table('duelist')->insert(['name' => 'Carly Carmine']);
        DB::table('duelist')->insert(['name' => 'Crow Hogan']);
        DB::table('duelist')->insert(['name' => 'Devack']);
        DB::table('duelist')->insert(['name' => 'Dragan']);
        DB::table('duelist')->insert(['name' => 'Greiger']);
        DB::table('duelist')->insert(['name' => 'Halldor']);
        DB::table('duelist')->insert(['name' => 'Hunter Pace']);
        DB::table('duelist')->insert(['name' => 'Jack Atlas']);
        DB::table('duelist')->insert(['name' => 'Jean']);
        DB::table('duelist')->insert(['name' => 'Kalin Kessler']);
        DB::table('duelist')->insert(['name' => 'Leo']);
        DB::table('duelist')->insert(['name' => 'Lester']);
        DB::table('duelist')->insert(['name' => 'Misty Tredwell']);
        DB::table('duelist')->insert(['name' => 'Mr. Armstrong']);
        DB::table('duelist')->insert(['name' => 'Primo']);
        DB::table('duelist')->insert(['name' => 'Rex Goodwin']);
        DB::table('duelist')->insert(['name' => 'Roman Goodwin']);
        DB::table('duelist')->insert(['name' => 'Sayer']);
        DB::table('duelist')->insert(['name' => 'Sherry LeBlanc']);
        DB::table('duelist')->insert(['name' => 'Tetsu Trudge']);
        DB::table('duelist')->insert(['name' => 'Yusei Fudo']);
        DB::table('duelist')->insert(['name' => 'Zone']);
        DB::table('duelist')->insert(['name' => 'Alito']);
        DB::table('duelist')->insert(['name' => 'Anna Kaboom']);
        DB::table('duelist')->insert(['name' => 'Astral']);
        DB::table('duelist')->insert(['name' => 'Bronk Stone']);
        DB::table('duelist')->insert(['name' => 'Cathy Katherine']);
        DB::table('duelist')->insert(['name' => 'Dextra']);
        DB::table('duelist')->insert(['name' => 'Don Thousand']);
        DB::table('duelist')->insert(['name' => 'Dr. Faker']);
        DB::table('duelist')->insert(['name' => 'Dumon']);
        DB::table('duelist')->insert(['name' => 'Flip Turner']);
        DB::table('duelist')->insert(['name' => 'Girag']);
        DB::table('duelist')->insert(['name' => 'Kite Tenjo']);
        DB::table('duelist')->insert(['name' => 'Mizar']);
        DB::table('duelist')->insert(['name' => 'Nash']);
        DB::table('duelist')->insert(['name' => 'Nelson Andrews']);
        DB::table('duelist')->insert(['name' => 'Nistro']);
        DB::table('duelist')->insert(['name' => 'Number 96']);
        DB::table('duelist')->insert(['name' => 'Quattro']);
        DB::table('duelist')->insert(['name' => 'Quinton']);
        DB::table('duelist')->insert(['name' => 'Ray Shadows']);
        DB::table('duelist')->insert(['name' => 'Reginald Kastle']);
        DB::table('duelist')->insert(['name' => 'Rio Kastle']);
        DB::table('duelist')->insert(['name' => 'Trey']);
        DB::table('duelist')->insert(['name' => 'Vector']);
        DB::table('duelist')->insert(['name' => 'Vetrix']);
        DB::table('duelist')->insert(['name' => 'Yuma Tsukumo']);
        DB::table('duelist')->insert(['name' => 'ZEXAL']);
        DB::table('duelist')->insert(['name' => 'ZEXAL 3']);
        DB::table('duelist')->insert(['name' => 'Aura Sentia']);
        DB::table('duelist')->insert(['name' => 'Celina']);
        DB::table('duelist')->insert(['name' => 'Chojiro Tokumatsu']);
        DB::table('duelist')->insert(['name' => 'Declan Akaba']);
        DB::table('duelist')->insert(['name' => 'Dennis McField']);
        DB::table('duelist')->insert(['name' => 'Dipper O\'rion']);
        DB::table('duelist')->insert(['name' => 'Gong Strong']);
        DB::table('duelist')->insert(['name' => 'Jean Michel Roget']);
        DB::table('duelist')->insert(['name' => 'Julia Krystal']);
        DB::table('duelist')->insert(['name' => 'Kit Blade']);
        DB::table('duelist')->insert(['name' => 'Lulu']);
        DB::table('duelist')->insert(['name' => 'Moon Shadow']);
        DB::table('duelist')->insert(['name' => 'Obelisk Force']);
        DB::table('duelist')->insert(['name' => 'Officer 227']);
        DB::table('duelist')->insert(['name' => 'Rin']);
        DB::table('duelist')->insert(['name' => 'Shay Obsidian']);
        DB::table('duelist')->insert(['name' => 'Sora Perse']);
        DB::table('duelist')->insert(['name' => 'Sylvio Sawatari']);
        DB::table('duelist')->insert(['name' => 'The Sledgehammer']);
        DB::table('duelist')->insert(['name' => 'Yugo']);
        DB::table('duelist')->insert(['name' => 'Yuri']);
        DB::table('duelist')->insert(['name' => 'Yusho Sakaki']);
        DB::table('duelist')->insert(['name' => 'Yuto']);
        DB::table('duelist')->insert(['name' => 'Yuya Sakaki']);
        DB::table('duelist')->insert(['name' => 'Z-ARC']);
        DB::table('duelist')->insert(['name' => 'Zuzu Boyle']);
        DB::table('duelist')->insert(['name' => 'Ai']);
        DB::table('duelist')->insert(['name' => 'Akira Zaizen']);
        DB::table('duelist')->insert(['name' => 'Blue Angel']);
        DB::table('duelist')->insert(['name' => 'Blue Gal']);
        DB::table('duelist')->insert(['name' => 'Blue Maiden']);
        DB::table('duelist')->insert(['name' => 'Bohman']);
        DB::table('duelist')->insert(['name' => 'Ghost Gal']);
        DB::table('duelist')->insert(['name' => 'Knight of Hanoi']);
        DB::table('duelist')->insert(['name' => 'Lightning']);
        DB::table('duelist')->insert(['name' => 'Playmaker']);
        DB::table('duelist')->insert(['name' => 'Roboppi']);
        DB::table('duelist')->insert(['name' => 'Soulburner']);
        DB::table('duelist')->insert(['name' => 'Spectre']);
        DB::table('duelist')->insert(['name' => 'The Gore']);
        DB::table('duelist')->insert(['name' => 'The Shepherd']);
        DB::table('duelist')->insert(['name' => 'Varis']);
        DB::table('duelist')->insert(['name' => 'Windy']);
    }
}
